---
name: Build and Publish Apptainer Image

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PYTORCH_VERSION: "2.4.0"
  CUDA_VERSION: "12.1"
  CUDNN_VERSION: "9"
  APPTAINER_VERSION: "1.3.0"

jobs:
  build-apptainer-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: ${{ env.APPTAINER_VERSION }}

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            apptainer remote login -u ${{ github.actor }} \
            --password-stdin oras://ghcr.io

      - name: Build Apptainer image
        run: |
          apptainer build pytorch.sif pytorch.def

      - name: Push to GitHub Container Registry
        if: github.event_name != 'pull_request'
        run: |
          IMAGE_BASE="oras://ghcr.io/${{ github.repository }}/pytorch"
          apptainer push pytorch.sif \
            ${IMAGE_BASE}:${{ env.PYTORCH_VERSION }}
          apptainer push pytorch.sif ${IMAGE_BASE}:latest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytorch-apptainer-image
          path: pytorch.sif
          retention-days: 7
