---
name: Build and Publish Apptainer Image

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apptainer-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.0

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            apptainer remote login -u ${{ github.actor }} \
            --password-stdin oras://ghcr.io

      - name: Build Apptainer image
        run: |
          apptainer build pytorch.sif pytorch.def

      - name: Push to GitHub Container Registry
        if: github.event_name != 'pull_request'
        run: |
          apptainer push pytorch.sif \
            oras://ghcr.io/${{ github.repository }}/pytorch:2.4.0
          apptainer push pytorch.sif \
            oras://ghcr.io/${{ github.repository }}/pytorch:latest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytorch-apptainer-image
          path: pytorch.sif
          retention-days: 7
